### ISSUE TITLE
librSPDE.so disappears after installing the Centos7 build (01/12/2024 devel version)

### ISSUE THREAD

**Issue by osupplisson** [hrue/r-inla#106]
Hi,

I don't know if I should post this here or on the rSPDE github (cc @vpnsctl).

I wanted to try the new anisotropic model from the rSPDE package, added in the 01/12/2024 devel version of the R-INLA package but I faced the following problem:

After installing the package from scratch, the `INLA/bin/linux/64bit/external/rSPDE` folder on the HPC was looking like this:

![image](https://github.com/user-attachments/assets/306e9039-7fd7-44fc-83eb-d01734b5397e)

However, after installing the Centos7 build (`./CentOS Linux-7 (Core)/Version_24.12.01/64bit.tgz`), the `librSPDE.so` disappeared:

![image](https://github.com/user-attachments/assets/54392d47-a10f-4437-b0b0-fac0ea2ac354)

which yielded the following error when trying to setup the model:

```
Error in path.expand(path) : invalid 'path' argument
Calls: source ... do.call -> <Anonymous> -> normalizePath -> path.expand
In addition: Warning messages:
 In normalizePath(paste0(dirname(inla.call.builtin()), "/external/",  :
  path[1]="/home/osupplisson/R/x86_64-pc-linux-gnu-library/4.4/INLA/bin/linux/64bit/external/rSPDE/librSPDE.so": No such file or directory
Execution halted
```
The same problem also appeared on a second HPC, also using the Centos7 build.

Best,
Olivier

Ps: I was also working with the last rSPDE devel version.
Ps2: everything runs perfectly on my windows laptop, thank you very much for adding this model!

**Comment by hrue** [comment]
Let me check

--
Håvard Rue
Professor of Statistics
Statistics Program, CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900, Saudi Arabia
Email: ***@***.***
Office: +966 (0)12 808 0640
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
On 1 Dec 2024 at 18:47 +0300, Olivier Supplisson ***@***.***>, wrote:
> Hi,
> I don't know if I should post this or on the rSPDE github (cc @vpnsctl).
> I wanted to try the new anisotropic model from the rSPDE package, added in the 01/12/2024 devel version of the R-INLA package but I faced the following problem:
> After installing the package from scratch, the INLA/bin/linux/64bit/external/rSPDE folder on the HPC was looking like this:
> image.png (view on web)
> However, after installing the Centos7 build (./CentOS Linux-7 (Core)/Version_24.12.01/64bit.tgz), the librSPDE.so disappeared:
> image.png (view on web)
> which yielded the following error when trying to setup the model:
> Error in path.expand(path) : invalid 'path' argument
> Calls: source ... do.call -> <Anonymous> -> normalizePath -> path.expand
> In addition: Warning messages:
> In normalizePath(paste0(dirname(inla.call.builtin()), "/external/",  :
>  path[1]="/home/osupplisson/R/x86_64-pc-linux-gnu-library/4.4/INLA/bin/linux/64bit/external/rSPDE/librSPDE.so": No such file or directory
> Execution halted
> The same problem also appeared on a second HPC, also using the Centos7 build.
> Best,
> Olivier
> Ps: I was also working with the last rSPDE devel version.
> Ps2: everything runs perfectly on my windows laptop, thank you very much !
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by hrue** [comment]
see if 

inla.binary.install()

for Rocky8 will work

issue is that CentOS7 is past 'end of life' and no longer supported. All the
repo's are down...

On Sun, 2024-12-01 at 07:47 -0800, Olivier Supplisson wrote:
> Hi,
> I don't know if I should post this or on the rSPDE github (cc @vpnsctl).
> I wanted to try the new anisotropic model from the rSPDE package, added in the
> 01/12/2024 devel version of the R-INLA package but I faced the following
> problem:
> After installing the package from scratch, the
> INLA/bin/linux/64bit/external/rSPDE folder on the HPC was looking like this:
> image.png (view on web)
> However, after installing the Centos7 build (./CentOS Linux-7
> (Core)/Version_24.12.01/64bit.tgz), the librSPDE.so disappeared:
> image.png (view on web)
> which yielded the following error when trying to setup the model:
> Error in path.expand(path) : invalid 'path' argument
> Calls: source ... do.call -> <Anonymous> -> normalizePath -> path.expand
> In addition: Warning messages:
>  In normalizePath(paste0(dirname(inla.call.builtin()), "/external/",  :
>   path[1]="/home/osupplisson/R/x86_64-pc-linux-gnu-
> library/4.4/INLA/bin/linux/64bit/external/rSPDE/librSPDE.so": No such file or
> directory
> Execution halted
> The same problem also appeared on a second HPC, also using the Centos7 build.
> Best,
> Olivier
> Ps: I was also working with the last rSPDE devel version.
> Ps2: everything runs perfectly on my windows laptop, thank you very much !
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by osupplisson** [comment]
Thank you very much for your reply and identifying the issue: it is indeed working with Rocky8.

Best,
Olivier

**Comment by hrue** [comment]
The issue was that recent rSPDE code needed gcc at least version 9. I managed to
upgrade the compiler and now CentOS7 should be fine with most recent testing.

Anyway, CentOS7 support will be stopped end of year, as it reached end-of-life
June 30 2024, hence not longer supported or updated





On Sun, 2024-12-01 at 10:10 -0800, Olivier Supplisson wrote:
> Thank you very much for your reply and identifying the issue: it is indeed
> working with Rocky8.
> Best,
> Olivier
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.
