### ISSUE TITLE
missing Windows binaries for stable INLA in R 4.0

### ISSUE THREAD

**Issue by bastistician** [hrue/r-inla#24]
The [*stable* INLA repository](https://inla.r-inla-download.org/R/stable/bin/windows/contrib/4.0/) which I reference from my package to install INLA currently does not contain any Windows binaries for R 4.0. The [*testing* repository](https://inla.r-inla-download.org/R/testing/bin/windows/contrib/4.0/) does provide such Windows binaries. Maybe one of those binaries could be copied over to stable?

**Comment by hrue** [comment]
Yes.  Soon

—
Håvard Rue
Professor of Statistics
Statistics Program, CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900, Saudi Arabia

Email: haavard.rue@kaust.edu.sa
Office: +966 (0)12 808 0640
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

**Comment by hrue** [comment]
I'll add this soon. meanwhile, please use the testing version (just
replace /stable with /testing, and its there)


On Fri, 2021-01-29 at 15:11 +0000, Sebastian Meyer wrote:
> The stable INLA repository which I reference from my package to
> install INLA currently does not contain any Windows binaries for R
> 4.0. The testing repository does provide such Windows binaries. Maybe
> one of those binaries could be copied over to stable?
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
Håvard Rue
Professor of Statistics
Statistics Program, CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900, Saudi Arabia

Email: haavard.rue@kaust.edu.sa
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

**Comment by hrue** [comment]
Its there now.

**Comment by hrue** [comment]
issue is fixed

**Comment by bastistician** [comment]
Great, thanks!
