### ISSUE TITLE
warning when saving inla object with saveRDS()

### ISSUE THREAD

**Issue by ThierryO** [hrue/r-inla#37]
I'm getting the warning message `'package:stats' may not be available when loading`.

I've narrowed the problem to be in three locations of the inla object.

```
Model[["all.hyper"]][["random"]][[1]][["hyper"]][["theta"]][["to.theta"]]
Model[["all.hyper"]][["random"]][[1]][["hyper"]][["theta"]][["from.theta"]]
Model[[".args"]][[".parent.frame"]]
```

**Comment by finnlindgren** [comment]
The to.theta and from.theta entries are function objects, and the `.parent.frame` is a pointer to the calling environment for the inla call, so it's likely attempting to save more of the global R environment than necessary. For .args, I think it just saves everything in the inla input to ensure one can rerun the inla call, but it should in principle not need to save _everything_, just the parts actually needed.

**Comment by hrue** [comment]
Close
