### ISSUE TITLE
Problems with INLA installation

### ISSUE THREAD

**Issue by LilianeTrafelet** [hrue/r-inla#38]
Hi

I have a problem installing the INLA package. I get the following error:

_* installing *binary* package 'INLA' ...
cp: unknown option -- )
Try '/usr/bin/cp --help' for more information.
ERROR: installing binary package failed
* removing 'C:/Program Files/R/R-4.0.2/library/INLA'
Warning in install.packages :
  installation of package ‘INLA’ had non-zero exit status
The downloaded source packages are in
	‘C:\Users\U80864263\AppData\Local\Temp\Rtmp69tlBB\downloaded_packages’_

I used the following command to try to install it:

_install.packages("INLA", repos=c(getOption("repos"), INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)_

In the given path (......\downloaded_packages), there is an INLA_21.11.22.tar.gz file (81.7 Mb).

Do you know how I could solve this problem?

Best wishes

**Comment by hrue** [comment]
try again after upgrading to R-4.1




On Fri, 2022-01-21 at 06:41 -0800, LilianeTrafelet wrote:
> Hi
> I have a problem installing the INLA package. I get the following
> error:
> _* installing binary package 'INLA' ...
> cp: unknown option -- )
> Try '/usr/bin/cp --help' for more information.
> ERROR: installing binary package failed
>  * removing 'C:/Program Files/R/R-4.0.2/library/INLA'
>    Warning in install.packages :
>    installation of package ‘INLA’ had non-zero exit status
>    The downloaded source packages are in
>    ‘C:\Users\U80864263\AppData\Local\Temp\Rtmp69tlBB\downloaded_packag
> es’_
> I used the following command to try to install it:
> install.packages("INLA", repos=c(getOption("repos"),
> INLA="https://inla.r-inla-download.org/R/stable"), dep=TRUE)
> In the given path (......\downloaded_packages), there is an
> INLA_21.11.22.tar.gz file (81.7 Mb).
> Do you know how I could solve this problem?
> Best wishes
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

-- 
Håvard Rue
Professor of Statistics, CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900, Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
Zoom.office: Meeting ID 510 522 9264

**Comment by LilianeTrafelet** [comment]
Hi

Thanks for your quick response
The issue is that I have to use the same R version as my collegues. However, they were able to install INLA with without issues using the same R version as me.

**Comment by hrue** [comment]
R-4.0 and R-4.1 should just be a minor upgrade. we do not build INLA for
R-4.0 anymore, so you might run into R-issues as well at some point
using R-4.0


On Fri, 2022-01-21 at 07:26 -0800, LilianeTrafelet wrote:
> Hi
> Thanks for your quick response
> The issue is that I have to use the same R version as my collegues.
> However, they were able to install INLA with without issues using the
> same R version as me.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you commented.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics, CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900, Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
Zoom.office: Meeting ID 510 522 9264
