### ISSUE TITLE
inla.mesh.2d never finishes

### ISSUE THREAD

**Issue by sjbonner** [hrue/r-inla#39]
Hi @hrue et al,

I'm hoping you can help me with what seems to be an OS specific issue. 

I'm trying to run the code from Opitz (2017) "Latent Gaussian modeling and INLA: A review with focus on space-time applications " ([https://arxiv.org/abs/1708.02723](url)). I have successfully run the code on a Mac, but I cannot get it to work properly on two different installations of Ubuntu Linux 20.04.3 (one native and one run through WSL on Windows). The failure occurs with the command:
```
mesh.sim=inla.mesh.2d(boundary=list(segm.bnd,segm.bnd.ext),
                      max.edge=c(.04,.2),
                      min.angle=21)

```
This completes in a minute or two on my Mac, but the command never completes on the Linux machines. I've waited up to a couple of hours to be sure. When I interrupt the command I receive the error: `
Error in fmesher.read(prefix, "manifold") : 
  File '/tmp/RtmpQ5Naxy/fmesher10dd0a8fdc.manifold' does not exist`

Listing the contents of this directory shows

```
$ ls /tmp/RtmpQ5Naxy/                           
fmesher10dd0a8fdc.input.s             fmesher10dd0a8fdc.input.segm.int.grp  libloc_174_173b0d0583319ed2.rds            fmesher10dd0a8fdc.input.segm.bnd.grp  fmesher10dd0a8fdc.input.segm.int.idx  libloc_198_6c6d31b77eb27d50.rds            fmesher10dd0a8fdc.input.segm.bnd.idx  libloc_169_8f48fc7d1db1bb3e.rds  
```

I noticed a previous issue concerning fmesher (#8), but it has been closed. I believe that all of my libraries and the INLA package are up-to-date. I have tried running
```
INLA:::inla.binary.install()
```
but the behaviour persists. 

I've copied my sessionInfo() along with the MWE below.

Apologies if this issue has already been addressed. 

Thanks!

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
[1] INLA_22.01.25 sp_1.4-5      foreach_1.5.1 Matrix_1.4-0 

loaded via a namespace (and not attached):
[1] compiler_4.1.2   rgdal_1.5-28     tools_4.1.2      splines_4.1.2   
[5] codetools_0.2-18 grid_4.1.2       iterators_1.0.13 lattice_0.20-45 
> 
```

MWE adapted from [](https://arxiv.org/abs/1708.02723)
```
library(INLA)

nodes.bnd=matrix(c(0,0,1,0,1,1,0,1),ncol=2,byrow=T)
segm.bnd=inla.mesh.segment(nodes.bnd)

nodes.bnd.ext=matrix(c(-.5,-.5,1.5,-.5,1.5,1.5,-.5,1.5),ncol=2,byrow=T)
segm.bnd.ext=inla.mesh.segment(nodes.bnd.ext)

mesh.sim=inla.mesh.2d(boundary=list(segm.bnd,segm.bnd.ext),
                      max.edge=c(.04,.2),
                      min.angle=21)
```

**Comment by finnlindgren** [comment]
Please try setting the `max.n.strict` and `max.n` arguments to `inla.mesh.2d` to eliminate one potential issue:
```
max.n.strict	
The maximum number of vertices allowed, overriding min.angle and max.edge (default=-1, meaning no limit).
One or two values, where the second value gives the number of additional vertices allowed for the extension.

max.n	
The maximum number of vertices allowed, overriding max.edge only (default=-1, meaning no limit).
One or two values, where the second value gives the number of additional vertices allowed for the extension.
```
That will protect it against adding an infinite number of vertices for problematic geometries.

However, a more likely reason is if your input geometry is "too perfect"; there are some rare cases where e.g. input points on a perfect square can give undetected infinite loops where it can't numerically decide between two in theory equally good triangulations (these things can be notoriously difficult to detect, but the code catches most of those issues). A simple solution to that type of issue is usually to nudge the input point by small random amounts, e.g. via `loc+matrix(runif(2*n) * 1e-9, n, 2)` where `n=nrow(loc)`. Since nodes.bnd in your code seems to be a perfect square, my guess is that's the issue. Whether this issue is triggered unfortunately depends on the specific floating point details of the system and compiler optimisations, so it's difficult to debug.

**Comment by finnlindgren** [comment]
Since you say it takes a minute or two to complete on a Mac, it may even be a combination of the two issues I mentioned; For most meshes, it should only take a few seconds to complete. How many vertices (`mesh$n`) are generated when you run on Mac?

**Comment by sjbonner** [comment]
I have to admit that I lied in a little in my first post. My Mac is my home computer, so I didn't have it on hand during the day. I tried again and the actual time was less than 5 seconds. I just tested with random noise on Linux and it finished in seconds too.

Thanks so much for your help @finnlindgren!
