### ISSUE TITLE
Running crashed

### ISSUE THREAD

**Issue by willright28** [hrue/r-inla#42]
Hi all,

I am a beginner with R-inla. I try to use an R package named gINLAnd which needs the R-inla installed.
I'm using R 4.1.0 in windows 10. The R-inla was installed following this website: https://www.r-inla.org/download-install. And the testing version was chosen.
Everything seems fine when installing and testing the two packages. But something was wrong when I tried to use the gINLAnd package.
The error message said: "*** ERROR ***         Dimension of the MVNORM prior is not equal to number of used hyperparameters: 1 != 0". But I can't find a similar question in the group, so anyone could help me with this?

Thanks in advance!

**Comment by hrue** [comment]
This is answered elsewhere
