### ISSUE TITLE
binaries not available?

### ISSUE THREAD

**Issue by mca91** [hrue/r-inla#43]
Not sure whether this is related to this repository but R package binaries for the stable versions (on both macOS and Windows) are unavailable at https://inla.r-inla-download.org/stable/bin since yesterday. `install.packages()` throws a 404 error.

**Comment by finnlindgren** [comment]
Where did the url come from? In my scripts I have `https://inla.r-inla-download.org/R/stable` and  `https://inla.r-inla-download.org/R/testing`, and https://inla.r-inla-download.org/R/stable/bin seems to have the right folders/files.

**Comment by finnlindgren** [comment]
The information on https://www.r-inla.org/download-install also has `.../R/stable` and not `.../stable`. I have
```
local({
  r <- c(INLA = "https://inla.r-inla-download.org/R/testing",
         CRAN = "https://cloud.r-project.org/")
    options(repos = r)
})
```
in my `.Rprofile`.

**Comment by hrue** [comment]
I had to clean up the www-repo as it simply got too huge, and I forgot a ``|grep -v /stable'', hence I see I deleted one (I think) stable build. But I found it on the www-server's backup and I should be there now. Let us know if there are still issues.

**Comment by mca91** [comment]
You're right @finnlindgren, I missed the `\R\` in my URL (typed it by hand). This is where the `.tgz` file was missing... got confused yesterday while setting up a new notebook when I copy-pasted the command from https://www.r-inla.org/download-install and got said 404 error in R. @hrue I just checked; works fine again, thanks!

**Comment by hrue** [comment]
thx. I'll close this issue.
