### ISSUE TITLE
Error when deploying a Shiny app with INLA

### ISSUE THREAD

**Issue by PauGallesClara** [hrue/r-inla#46]
Hi ! 
I've made an rmarkdown projecte with output: html and runtime: shiny with some bayesian modelling using INLA. It works well locally, but when trying to publish it in to my account I get this error and the app is not able to be deployed:

Error: Unhandled Exception: Child Task 1156373091 failed: Error building image: Error fetching INLA (21.11.22) source. <CRANPackageSource repo='http://cran.rstudio.org'> unable to satisfy package: INLA (21.11.22)

Any idea to solve this?

Pau

**Comment by finnlindgren** [comment]
It looks like in 2015 this was possible by setting up the repository options before doing the local INLA install (https://github.com/rstudio/rsconnect/issues/88), to allow rsconnect to know from where to install the package:
```
options(repos = c("INLA"="https://inla.r-inla-download.org/R/testing", "CRAN"="https://cran.rstudio.org"))
install.packages("INLA")
```
However, in this link from last year, https://groups.google.com/g/shiny-discuss/c/mjrutgFNSFg, someone tried a version of the above, but an RStudio person says that shinyapps can only handle CRAN, Bioconductor, and github packages; unfortunately you need the binary INLA install, so the fact that the INLA code is on github doesn't help you.

I would try to 2015 version and see if it actually still works.
(If that doesn't work, there might still be a way that someone else knows about.)
A full solution to this would be if INLA could be easily built from source upon installation, but we don't have a build system capable of that.

(Above I assumed you were trying to deploy on shinyapps.io; if you have your own server, you should be able to configure that server to have INLA available in some way.)

**Comment by PauGallesClara** [comment]
Hi !!

I had the idea of modelling outside the rmarkdown to creat the map objects, and then call them and save them in the same folder. Hence, I won't need the INLA library inside the rmarkdown file. I've tried it and it seems to work (now I'm struggling to publish it in the server but I get other errors, related on the connection of the shiny server... but that's another story) 

Thank you for your quick answer.
