### ISSUE TITLE
different DIC for the same model and data using two computers

### ISSUE THREAD

**Issue by wanxinru** [hrue/r-inla#49]
I'm using a workstation for parallel computing of multiple INLA models, but when I'm checking the DIC of the best model using my laptop, I find a small difference in DIC between the two computers for the same model and data.

Then I update the INLA and R to the same version (v22.9.2 and v4.2.1), but the question is still there (the 2 screenshots below), did anybody encounters the same issue?

![image](https://user-images.githubusercontent.com/22925894/189582166-32dd5c29-11b9-423c-914c-3c719baae781.png)
![image](https://user-images.githubusercontent.com/22925894/189582173-094a704f-73b6-4984-8f33-32993b20b984.png)

**Comment by hrue** [comment]
Due to the parallel computations the intitial values will be more random
for the inner optimization for each thread.

the DIC values are additive so small changes can add up to larger
numbers. 

you can try to add

	r <- inla(...)
	r <- inla.rerun(r)

which which do a restart and stabalize the results

On Sun, 2022-09-11 at 22:50 -0700, wan xinru wrote:
> I'm using a workstation for parallel computing of multiple INLA
> models, but when I'm checking the DIC of the best model using my
> laptop, I find a small difference in DIC between the two computers for
> the same model and data.
> Then I update the INLA and R to the same version (v22.9.2 and v4.2.1),
> but the question is still there (the 2 screenshots below), did anybody
> encounters the same issue?
> image
> image
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
Zoom.office: Meeting ID 510 522 9264

**Comment by wanxinru** [comment]
Thanks for your instant suggestion, this is important for reproducible research, I've added this in the parallel computation, hopefully, I can get a consistent result.

Best regards,
Xinru


> Due to the parallel computations the intitial values will be more random for the inner optimization for each thread. the DIC values are additive so small changes can add up to larger numbers. you can try to add r <- inla(...) r <- inla.rerun(r) which which do a restart and stabalize the results
> […](#)
> On Sun, 2022-09-11 at 22:50 -0700, wan xinru wrote: I'm using a workstation for parallel computing of multiple INLA models, but when I'm checking the DIC of the best model using my laptop, I find a small difference in DIC between the two computers for the same model and data. Then I update the INLA and R to the same version (v22.9.2 and v4.2.1), but the question is still there (the 2 screenshots below), did anybody encounters the same issue? image image — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> -- Håvard Rue Professor of Statistics Statistics Program CEMSE Division King Abdullah University of Science and Technology Thuwal 23955-6900 Kingdom of Saudi Arabia ***@***.*** Office: +966 (0)12 808 0640   Mobile: +966 (0)54 470 0421 Research group: bayescomp.kaust.edu.sa   R-INLA project: [www.r-inla.org](http://www.r-inla.org) Zoom: kaust.zoom.us/my/haavard.rue Zoom.office: Meeting ID 510 522 9264
