### ISSUE TITLE
[Improvement] Adding censored (cenpoisson2-like) negative binomial likelihood ? 

### ISSUE THREAD

**Issue by osupplisson** [hrue/r-inla#53]
Dear INLA Team,

First of all, thank you very much for your package and all your work to make it quite easy to use/understand.

There have been some work showing that for modelling infectious diseases, negative binomial might be better than poisson. 

I'd like to use INLA in this context and therefore use this density function for the likelihood. However, I have censored data (each of the 100+ area having its own censorship). 

I was thus wondering if it would be possible, despite the very peculiar demand, to append the package to provide as additional likelihood a censored version (cenpoisson2-like) for negative binomial (and maybe other zero-inflated likelihood, because I assume zeroinflatedcenpoisson0/1 are cenpoisson1-like) ?

That would be greatly appreciated and expand the use of R INLA to different data context.

Best,
Olivier

**Comment by hrue** [comment]
Let me check this out

**Comment by hrue** [comment]
I have added cennbinomial2, which is similar to the cenpoisson2. I will likely build a new version tonight so you can try it out

**Comment by osupplisson** [comment]
Thank you so much for your time/responsiveness! 

I am looking forward to giving it a try and let you know if I have any warning coming out.

**Comment by hrue** [comment]
You can try inla.doc("cennbinomial2") in the new testing version. Please let me know how this goes

**Comment by osupplisson** [comment]
I just gave it a try with a fairly complex spatio-temporal model: it worked like a charm ! 

I'll let you know if I find anything strange once I get deeper in the analysis.

Thank you very much for adding that option so quickly.

Best,

**Comment by hrue** [comment]
Closed

**Comment by osupplisson** [comment]
Dear Professor Rue,

I gave it a closer look assuming that all variables were right censored (in INLA syntax L = y and H = Inf).

I tried with both a very complex model (model with P-splines for time, space, and space x time) and with the simple example from the vignette. In both cases INLA failed to estimate the model.

With the vignette's toy example, I tried the diagonal-based workaround (ie starting with diagonal = 10 then going down to 5 and finally 0, using each estimates as starting values). It indeed helped to obtain estimates. However, the estimates seems completely off.


## REPREX - NBin
`library(INLA)

n = 300
x = rnorm(n, sd = 0.2)
eta = 1 + x
E = runif(n, min = 0.5, max=2)
mu = E * exp(eta)
size = 1
y = rnbinom(n, size, mu=mu)

##All variables are right-censored
y.low <- y
y.high <- rep(Inf, n)
Y <- inla.mdata(cbind(y, y.low, y.high))

#Fail: either stop or returned only 0 for posteriors
r_1 = inla(Y ~ 1 + x,
         data = list(Y = Y, x = x, E = E),
         family = "cennbinomial2",
         E=E,
         verbose = T,
         control.inla = list(strategy = "simplified.laplace", int.strategy = "eb"))

#Using the diagonal trick 

r_1 = inla(Y ~ 1 + x,
           data = list(Y = Y, x = x, E = E),
           family = "cennbinomial2",
           E=E,
           verbose = T,
           control.inla = list(diagonal = 10, strategy = "simplified.laplace", int.strategy = "eb"))


r_2 = inla(Y ~ 1 + x,
           data = list(Y = Y, x = x, E = E),
           family = "cennbinomial2",
           E=E,
           verbose = T,
           control.mode = list(result = r_1, restart = TRUE),  
           control.inla = list(diagonal = 5, strategy = "simplified.laplace", int.strategy = "eb"))


r_3 = inla(Y ~ 1 + x,
           data = list(Y = Y, x = x, E = E),
           family = "cennbinomial2",
           E=E,
           verbose = T,
           safe = T,
           control.mode = list(result = r_2, restart = TRUE),  
           control.inla = list(strategy = "simplified.laplace", int.strategy = "eb"))


summary(r_3)`


I gave it a try with the poisson version and it worked well without using the diagonal trick.

## REPREX - POISSON:
`library(INLA)

n = 300
x = rnorm(n, sd = 0.2)
eta = 1 + x
E = runif(n, min = 0.5, max=2)

mu = E * exp(eta)
size = 1
y = rpois(n,mu)
y.low <- y
y.high <- rep(Inf, n)
Y <- inla.mdata(cbind(y, y.low, y.high))

#Gave estimates and verbose seemed fine
r_1 = inla(Y ~ 1 + x,
         data = list(Y = Y, x = x, E = E),
         family = "cenpoisson2",
         E=E,
         verbose = T,
         control.inla = list(strategy = "simplified.laplace", int.strategy = "eb"))

summary(r_1)
`


I just wanted to double-check that there is no issue with how the likelihood is implemented ? It seems strange to me that it worked with the Poisson but not the Negative bin likelihood.

Especially, in the cennbin case, a lot of 'GMRFLib_2order_approx: rescue NAN/INF values in logl for idx=XX' appeared during the process.

Best,
Olivier

**Comment by hrue** [comment]
Seems like if all is right-censored, its harder to find the optimum. If can be that the overdispersion will have a confounding with the the fixed effects. Adding just a few real observed resolves the issue. 

if you set y.low=y, then you say that y.real >= y.low, if all are of this type, then you want to maximize Prob(y >= y.low), and here the random effect (which is what you essentially have with the nbinom), can also be used to increase this one

library(INLA)

n = 300
x = rnorm(n, sd = 0.2)
eta = 1 + x
E = runif(n, min = 0.5, max=2)
mu = E * exp(eta)
size = 1
y = rnbinom(n, size, mu=mu)

##All variables are right-censored
y.low <- y + rbinom(n, prob = 0.1, size = 2)
y.high <- rep(Inf, n)
Y <- inla.mdata(cbind(y, y.low, y.high))

#Fail: either stop or returned only 0 for posteriors
r_1 = inla(Y ~ 1 + x,
           data = list(Y = Y, x = x, E = E),
           family = "cennbinomial2",
           E=E,
           verbose = T,
           inla.mode = "experimental")
