### ISSUE TITLE
Latest testing version 22.10.05 crashes

### ISSUE THREAD

**Issue by frousseu** [hrue/r-inla#57]
The latest testing version seems to be broken.

```r
library(INLA)

## Le chargement a nécessité le package : Matrix
## Le chargement a nécessité le package : foreach
## Le chargement a nécessité le package : parallel
## Le chargement a nécessité le package : sp
## This is INLA_22.10.05 built 2022-10-05 12:59:18 UTC.
## - See www.r-inla.org/contact-us for how to get help.

r = inla(y ~ 1 ,data = data.frame(y=rnorm(100)), control.compute = list(config=TRUE))

## Error in inla.inlaprogram.has.crashed() : 
##   The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output ##  carefully.
##    If this does not help, please contact the developers at <help@r-inla.org>.

##   *** inla.core.safe:  inla.program has crashed: rerun to get better initial values. try=1/2 
##  Error in inla.inlaprogram.has.crashed() : 
##    The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output ##  carefully.
##    If this does not help, please contact the developers at <help@r-inla.org>.

##   *** inla.core.safe:  inla.program has crashed: rerun to get better initial values. try=2/2 
##  Error in inla.inlaprogram.has.crashed() : 
##    The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output ##  carefully.
##    If this does not help, please contact the developers at <help@r-inla.org>.
##  Erreur dans inla.core.safe(formula = formula, family = family, contrasts = contrasts,  : 
##    *** Fail to get good enough initial values. Maybe it is due to something else.

sessionInfo()

## R version 4.2.1 (2022-06-23 ucrt)
## Platform: x86_64-w64-mingw32/x64 (64-bit)
## Running under: Windows 10 x64 (build 17763)

##  Matrix products: default

##  locale:
##  [1] LC_COLLATE=French_Canada.1252  LC_CTYPE=French_Canada.1252    LC_MONETARY=French_Canada.1252 LC_NUMERIC=C                   ##  LC_TIME=French_Canada.1252    

##  attached base packages:
##  [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

##  other attached packages:
##  [1] INLA_22.10.05 sp_1.5-0      foreach_1.5.2 Matrix_1.4-1 

##  loaded via a namespace (and not attached):
##  [1] compiler_4.2.1     tools_4.2.1        MatrixModels_0.5-0 splines_4.2.1      codetools_0.2-18   grid_4.2.1         iterators_1.0.14  
##  lattice_0.20-45    fortunes_1.5-4  
```

**Comment by hrue** [comment]
You're right. I'm on it. 

On Wed, 2022-10-05 at 23:13 -0700, François Rousseu wrote:
> The latest testing version seems to be broken.
> library(INLA)
> 
> ## Le chargement a nécessité le package : Matrix
> ## Le chargement a nécessité le package : foreach
> ## Le chargement a nécessité le package : parallel
> ## Le chargement a nécessité le package : sp
> ## This is INLA_22.10.05 built 2022-10-05 12:59:18 UTC.
> ## - See www.r-inla.org/contact-us for how to get help.
> 
> r = inla(y ~ 1 ,data = data.frame(y=rnorm(100)), control.compute =
> list(config=TRUE))
> 
> ## Error in inla.inlaprogram.has.crashed() : 
> ##   The inla-program exited with an error. Unless you interupted it
> yourself, please rerun with verbose=TRUE and check the output ## 
> carefully.
> ##    If this does not help, please contact the developers at
> ***@***.***>.
> 
> ##   *** inla.core.safe:  inla.program has crashed: rerun to get
> better initial values. try=1/2 
> ##  Error in inla.inlaprogram.has.crashed() : 
> ##    The inla-program exited with an error. Unless you interupted it
> yourself, please rerun with verbose=TRUE and check the output ## 
> carefully.
> ##    If this does not help, please contact the developers at
> ***@***.***>.
> 
> ##   *** inla.core.safe:  inla.program has crashed: rerun to get
> better initial values. try=2/2 
> ##  Error in inla.inlaprogram.has.crashed() : 
> ##    The inla-program exited with an error. Unless you interupted it
> yourself, please rerun with verbose=TRUE and check the output ## 
> carefully.
> ##    If this does not help, please contact the developers at
> ***@***.***>.
> ##  Erreur dans inla.core.safe(formula = formula, family = family,
> contrasts = contrasts,  : 
> ##    *** Fail to get good enough initial values. Maybe it is due to
> something else.
> 
> sessionInfo()
> 
> ## R version 4.2.1 (2022-06-23 ucrt)
> ## Platform: x86_64-w64-mingw32/x64 (64-bit)
> ## Running under: Windows 10 x64 (build 17763)
> 
> ##  Matrix products: default
> 
> ##  locale:
> ##  [1] LC_COLLATE=French_Canada.1252  LC_CTYPE=French_Canada.1252   
> LC_MONETARY=French_Canada.1252 LC_NUMERIC=C                   ## 
> LC_TIME=French_Canada.1252    
> 
> ##  attached base packages:
> ##  [1] parallel  stats     graphics  grDevices utils     datasets 
> methods   base     
> 
> ##  other attached packages:
> ##  [1] INLA_22.10.05 sp_1.5-0      foreach_1.5.2 Matrix_1.4-1 
> 
> ##  loaded via a namespace (and not attached):
> ##  [1] compiler_4.2.1     tools_4.2.1        MatrixModels_0.5-0
> splines_4.2.1      codetools_0.2-18   grid_4.2.1        
> iterators_1.0.14  
> ##  lattice_0.20-45    fortunes_1.5-4  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
Zoom.office: Meeting ID 510 522 9264

**Comment by hrue** [comment]
should be fine now.


On Thu, 2022-10-06 at 10:57 +0300, Haavard Rue wrote:
> You're right. I'm on it. 
> 
> On Wed, 2022-10-05 at 23:13 -0700, François Rousseu wrote:
> > The latest testing version seems to be broken.
> > library(INLA)
> > 
> > ## Le chargement a nécessité le package : Matrix
> > ## Le chargement a nécessité le package : foreach
> > ## Le chargement a nécessité le package : parallel
> > ## Le chargement a nécessité le package : sp
> > ## This is INLA_22.10.05 built 2022-10-05 12:59:18 UTC.
> > ## - See www.r-inla.org/contact-us for how to get help.
> > 
> > r = inla(y ~ 1 ,data = data.frame(y=rnorm(100)), control.compute =
> > list(config=TRUE))
> > 
> > ## Error in inla.inlaprogram.has.crashed() : 
> > ##   The inla-program exited with an error. Unless you interupted it
> > yourself, please rerun with verbose=TRUE and check the output ## 
> > carefully.
> > ##    If this does not help, please contact the developers at
> > ***@***.***>.
> > 
> > ##   *** inla.core.safe:  inla.program has crashed: rerun to get
> > better initial values. try=1/2 
> > ##  Error in inla.inlaprogram.has.crashed() : 
> > ##    The inla-program exited with an error. Unless you interupted
> > it
> > yourself, please rerun with verbose=TRUE and check the output ## 
> > carefully.
> > ##    If this does not help, please contact the developers at
> > ***@***.***>.
> > 
> > ##   *** inla.core.safe:  inla.program has crashed: rerun to get
> > better initial values. try=2/2 
> > ##  Error in inla.inlaprogram.has.crashed() : 
> > ##    The inla-program exited with an error. Unless you interupted
> > it
> > yourself, please rerun with verbose=TRUE and check the output ## 
> > carefully.
> > ##    If this does not help, please contact the developers at
> > ***@***.***>.
> > ##  Erreur dans inla.core.safe(formula = formula, family = family,
> > contrasts = contrasts,  : 
> > ##    *** Fail to get good enough initial values. Maybe it is due to
> > something else.
> > 
> > sessionInfo()
> > 
> > ## R version 4.2.1 (2022-06-23 ucrt)
> > ## Platform: x86_64-w64-mingw32/x64 (64-bit)
> > ## Running under: Windows 10 x64 (build 17763)
> > 
> > ##  Matrix products: default
> > 
> > ##  locale:
> > ##  [1] LC_COLLATE=French_Canada.1252  LC_CTYPE=French_Canada.1252  
> > LC_MONETARY=French_Canada.1252 LC_NUMERIC=C                   ## 
> > LC_TIME=French_Canada.1252    
> > 
> > ##  attached base packages:
> > ##  [1] parallel  stats     graphics  grDevices utils     datasets 
> > methods   base     
> > 
> > ##  other attached packages:
> > ##  [1] INLA_22.10.05 sp_1.5-0      foreach_1.5.2 Matrix_1.4-1 
> > 
> > ##  loaded via a namespace (and not attached):
> > ##  [1] compiler_4.2.1     tools_4.2.1        MatrixModels_0.5-0
> > splines_4.2.1      codetools_0.2-18   grid_4.2.1        
> > iterators_1.0.14  
> > ##  lattice_0.20-45    fortunes_1.5-4  
> > —
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> > You are receiving this because you are subscribed to this
> > thread.Message ID: ***@***.***>
> 

-- 
Håvard Rue
Professor of Statistics
Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
Zoom.office: Meeting ID 510 522 9264

**Comment by hrue** [comment]
closed
