### ISSUE TITLE
How can I get the sd of a categorical factor in INLA model

### ISSUE THREAD

**Issue by wanxinru** [hrue/r-inla#64]
Hi,

I'm computing the contributions of different factors in a model, so all continuous factors were normalized and the mean of the slope was used for the calculation of factor contribution.

To get the sd of one categorical factor (as the contribution), I put the categorical factor in "iid" model: `y ~ X1 + f(X2, model = "iid")`, then get the sd by `bri.hyperpar.summary(model)`, is it the correct way to get the contribution of X2?

Best,
Xinru

**Comment by hrue** [comment]
Can you post this one to help@r-inla.org ?  thx

**Comment by wanxinru** [comment]
thanks, the post was transferred to [help@r-inla.org](mailto:help@r-inla.org)
