### ISSUE TITLE
spatio-temporal model - inla keeps crashing

### ISSUE THREAD

**Issue by nayanwij** [hrue/r-inla#77]
Hi, 
I have a spatio-temporal model that keeps crashing. I am using a grid of num [1:5293, 1:240]

The error I get is :

inla.mkl: src/inla.c:23905: inla_parse_ffield: Assertion `def->n > 1' failed.
Error in inla.inlaprogram.has.crashed() :
  The inla-program exited with an error. Unless you interupted it yourself, ple$
  If this does not help, please contact the developers at <help@r-inla.org>.
Calls: inla -> inla.inlaprogram.has.crashed
Execution halted

My code snippet is below:
df.st = data.frame(obs = as.vector(grid.data[,t]),
                   x = rep(grid.values$x, length(t)),
                   y = rep(grid.values$y, length(t)),
                   t = rep(t,each=(nrow(grid.values))),
                   dist_green = rep(dist_green_bycell, length(t)),
                   dist_mainroad = rep(dist_mainroad_bycell, length(t)),
                   dist_water=rep(dist_water_bycell,length(t)),
                   dist_playground=rep(dist_playground_bycell,length(t)),
                   dist_settlements=rep(dist_settlements_bycell,length(t)),
                   Population = rep(grid.values$Population, length(t)))

formula = obs ~ -1 + Intercept  + f(spatial.field, model = spde) + f(t, model='ar1') + offset(log(Population)) + dist_green+dist_mainroad +  dist_water + dist_playground + dist_settlements

#Stack creation and inla analysis
s.index <- inla.spde.make.index(name="spatial.field", n.spde=spde$n.spde) 
A.est = inla.spde.make.A(mesh=mesh,
                         loc=as.matrix(df.st[,c("x","y")]))
stack.est = inla.stack(data=list(obs=df.st$obs),
                       A=list(A.est,
                              1),
                       effects=list(c(s.index, list(Intercept=1)),
                                    list(df.st[,-1])),
                       tag='stdata')

output5 = inla(formula,
              data=inla.stack.data(stack.est),
              family="poisson",
              control.predictor=list(A=inla.stack.A(stack.est), compute =FALSE),
              control.fixed=list(expand.factor.strategy='inla'),
              #control.compute=list(config = TRUE, dic = TRUE, waic = TRUE),
              verbose=TRUE)

**Comment by nayanwij** [comment]
Hi,

Could I please have the solution you provided. I would like to save it.

Best wishes,

Nayantara

From: Håvard Rue ***@***.***>
Date: Tuesday, 19 March 2024 at 00:58
To: hrue/r-inla ***@***.***>
Cc: Nayantara Wijayanandana ***@***.***>, Author ***@***.***>
Subject: Re: [hrue/r-inla] spatio-temporal model - inla keeps crashing (Issue #77)

Closed #77<https://github.com/hrue/r-inla/issues/77> as completed.

**Comment by RealChrisxu** [comment]
So what is the solution? I really want the solution.
