### ISSUE TITLE
INLA not being installed properly on OSX when installing R from homebrew

### ISSUE THREAD

**Issue by AlexandreBSimas** [hrue/r-inla#84]
Hello, 

If I install `INLA` using the command:

```r
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)
```

from inside R that was installed from homebrew (default installation folder being `/opt/homebrew/Cellar/r/4.3.1/lib/R`), then `INLA` is not installed properly. Indeed, I get the same behavior that I have seen in the past in `r-hub`, etc., where that suggestion to use `inla.prune()` appears, together with the message "inla installation error". 

By looking at INLA's installation folder, it seems the linux version was installed. Indeed, it seems to be corroborated by looking at the file it downloads when installing `INLA` by using an R installation from homebrew. Indeed, I get:

```r
tentando a URL 'https://inla.r-inla-download.org/R/testing/src/contrib/INLA_23.11.01.tar.gz'
Content type 'application/x-gzip' length 76408272 bytes (72.9 MB)
```

whereas when I install `INLA` by using an R installation from CRAN's .pkg file, I get:

```r
tentando a URL 'https://inla.r-inla-download.org/R/testing/bin/macosx/big-sur-arm64/contrib/4.3/INLA_23.11.01.tgz'
Content type 'application/x-tar' length 45415739 bytes (43.3 MB)
```

which seems to be the correct address to download it.

Thank you. 

Best,
Alexandre

**Comment by hrue** [comment]
Homebrew R does not ‘work’, it’s something in its setup, which I have not looked into. Can u use CRAn R?

--
Håvard Rue
Professor of Statistics
Statistics Program, CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900, Saudi Arabia
Email: ***@***.***
Office: +966 (0)12 808 0640
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue
On 1 Nov 2023 at 22:47 +0300, Alexandre B. Simas ***@***.***>, wrote:
> Hello,
> If I install INLA using the command:
> install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)
> from inside R that was installed from homebrew (default installation folder being /opt/homebrew/bin/R, then INLA is not installed properly. Indeed, I get the same behavior that I have seen in the past in r-hub, etc., where that suggestion to use inla.prune() appears, together with the message "inla installation error".
> By looking at INLA's installation folder, it seems the linux version was installed. Indeed, it seems to be corroborated by looking at the file it downloads when installing INLA from homebrew. Indeed, I get:
> tentando a URL 'https://inla.r-inla-download.org/R/testing/src/contrib/INLA_23.11.01.tar.gz'
> Content type 'application/x-gzip' length 76408272 bytes (72.9 MB)
> whereas when I install INLA by using an R installation from CRAN's .pkg file, I get:
> tentando a URL 'https://inla.r-inla-download.org/R/testing/bin/macosx/big-sur-arm64/contrib/4.3/INLA_23.11.01.tgz'
> Content type 'application/x-tar' length 45415739 bytes (43.3 MB)
> which seems to be the correct address to download it.
> Thank you.
> Best,
> Alexandre
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by hrue** [comment]
On Wed, 2023-11-01 at 12:47 -0700, Alexandre B. Simas wrote:
> Hello,
> If I install INLA using the command:
> install.packages("INLA",repos=c(getOption("repos"),INLA="
> https://inla.r-inla-download.org/R/testing"), dep=TRUE)
> from inside R that was installed from homebrew (default installation 

This should be the correct way of specifying an external repo, and it
should be R's responsibility to get the correct package to install from
there.

I don't know why this happen. If you have a fix, please let me know

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by AlexandreBSimas** [comment]
Hi Håvard,

By playing a little bit, it seems that the homebrew version forces to install everything from source. So, it tried to download the corresponding version from source, but then, when it installs it does not have the binaries to execute inla. 

Probably this might be the issue that sometimes I had with these online testers that they had a bad installation. That they tried to install from source, from an OS which is not linux. Is it very bad to also add the binaries of inla for the other OS in the src version of inla? (From what I understand you added the linux binaries of inla in the bin folder in the src .tar.gz, right?)

If you are willing to try to generate some .tar.gz with inla binaries for mac-arm64 to test, just let me know, and I will be more than happy to test for you.

Best,
Alexandre

**Comment by hrue** [comment]
We had this behaviour before, when every installation had binaries for
all other OS's, which took quite some space. Therefore the function
'inla.prune()' which removed post-installation binaries not needed, and
then at some point, I did this when the package was installed, so that
only the binaries for that OS was installed and was in the package. This
lead to smaller package-size. 

Should be a way to install binaries if available, like

type = getOption("pkgType")

so by setting that option one could change the default behaviour.

so this option, if by default, different in CRAN R and homebrew R ? 



On Wed, 2023-11-01 at 23:54 -0700, Alexandre B. Simas wrote:
> Hi Håvard,
> By playing a little bit, it seems that the homebrew version forces to
> install everything from source. So, it tried to download the
> corresponding version from source, but then, when it installs it does
> not have the binaries to execute inla.
> Probably this might be the issue that sometimes I had with these
> online testers that they had a bad installation. That they tried to
> install from source, from an OS which is not linux. Is it very bad to
> also add the binaries of inla for the other OS in the src version of
> inla? (From what I understand you added the linux binaries of inla in
> the bin folder in the src .tar.gz, right?)
> If you are willing to try to generate some .tar.gz with inla binaries
> for mac-arm64 to test, just let me know, and I will be more than happy
> to test for you.
> Best,
> Alexandre
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by AlexandreBSimas** [comment]
Yes, exactly!
For homebrew I get:

```{r}
> getOption("pkgType")
[1] "source"
```

Maybe you can add in `INLA`'s home page with the installation instruction, so people can set it (even if temporarily) to install inla, then revert after if they want.

It definitely should solve the issue.

Thank you!

Best,
Alexandre

**Comment by hrue** [comment]
For CRAN R for Mac (Intel & M..) then the default is

> getOption("pkgType")
[1] "both"


yes, we need to add this to the home page


On Thu, 2023-11-02 at 00:05 -0700, Alexandre B. Simas wrote:
> Yes, exactly!
> For homebrew I get:
> > getOption("pkgType")
> [1] "source"
> Maybe you can add in INLA's home page with the installation
> instruction.
> It definitely should solve the issue.
> Thank you!
> Best,
> Alexandre
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by AlexandreBSimas** [comment]
Hi Håvard,

Thanks!

Tried here with homebrew, it is working now with this option!

I believe this should also be the issue with inla's installation in some machines (I have seen in the past on action, on r-hub, prob. on cran as well). They are probably trying to install from source. 

I believe you can close the issue, since I guess the best solution is just to add it in the installation instructions.

Once again, thanks.

**Comment by finnlindgren** [comment]
Setting the global option to "both" might break _other_ packages, if the reason they set it to "source" was to make sure the linking of other packages works correctly. If that's the case, then other packages may still need to be installed as "source", but one can then use `install.packages("INLA", type = "both", ...)` to locally override the global option (it has default `type = getOption("pkgType")`). However, the INLA dependencies might then need to be installed from "source" anyway, and that's more messy to deal with in the instructions. So if you can check whether other packages break when installed as "binary", that would help figure out what's the simplest correct option for INLA dependency installation would be.  For example, try installing any C/C++/Fortran containing R package with `type="binary"` and see if they work, e.g. `sf` or `terra`.

**Comment by AlexandreBSimas** [comment]
Hi Finn,

Good point. From the manual, apparently for unix type machines, the default is source (except from CRAN binaries):

on Unix-alikes
"source" (the default except under a CRAN macOS build), "mac.binary" and "both" (the default for CRAN macOS builds). 

I tried here with "mac.binary" (the same I used to install INLA on homebrew), but it does not allow "binary", says it is not supported:
```{r}
type 'binary' is not supported on this platform
```

When I tried to install `terra` and `sf` setting `type` to `mac.binary`, I got the following:
```{r}
Warning: unable to access index for repository https://cloud.r-project.org/bin/macosx/contrib/4.3:
  não foi possível abrir a URL 'https://cloud.r-project.org/bin/macosx/contrib/4.3/PACKAGES'

   package ‘terra’ is available as a source package but not as a binary

Warning message:
package ‘terra’ is not available as a binary package for this version of R
```

When I go to https://cloud.r-project.org/bin/macosx/contrib/ I see that they are available for R 4.2.

The same happens with `sf`. So, you are correct indeed. To further check, I removed everything and did a clean installation of homebrew, and *only* installed `INLA`, but now it broke (I believe because it did not install any dependency, it only installed inla):

```{r}
The downloaded binary packages are in
        /var/folders/sl/xc8t7y3d02x2y7mrnz7v2bld6gnj38/T//RtmpJdg1ZT/downloaded_packages
> library("INLA")
Carregando pacotes exigidos: Matrix
Carregando pacotes exigidos: sp

 *** caught segfault ***
address 0x0, cause 'invalid permissions'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 7: asNamespace(ns)
 8: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 9: loadNamespace(package, lib.loc)
10: doTryCatch(return(expr), name, parentenv, handler)
11: tryCatchOne(expr, names, parentenv, handlers[[1L]])
12: tryCatchList(expr, classes, parentenv, handlers)
13: tryCatch({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps, exclude, include.only)}, error = function(e) {    P <- if (!is.null(cc <- conditionCall(e)))         paste(" in", deparse(cc)[1L])    else ""    msg <- gettextf("package or namespace load failed for %s%s:\n %s",         sQuote(package), P, conditionMessage(e))    if (logical.return && !quietly)         message(paste("Error:", msg), domain = NA)    else stop(msg, call. = FALSE, domain = NA)})
14: library("INLA")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 
```

**Comment by finnlindgren** [comment]
You did `install.packages("INLA",type="mac.binary", ...)` ?

**Comment by AlexandreBSimas** [comment]
Yep:

```{r}
> install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE, type="mac.binary")
Installing package into ‘/opt/homebrew/lib/R/4.3/site-library’
```
