### ISSUE TITLE
dsparseModelMatrix in R -- INLA

### ISSUE THREAD

**Issue by CorentinVisee** [hrue/r-inla#85]
Hi there! 

I have a question about this simple example presented on the website:

### Reproducible example

``` r
library(INLA)
n = 100
a = 1
b = 1
tau = 100
z = rnorm(n)
eta = a + b * z

scale = exp(rnorm(n))
prec = scale * tau
y = rnorm(n, mean = eta, sd = 1 / sqrt(prec))

data = list(y = y, z = z)
formula = y ~ 1 + z
result = inla(formula, family = "gaussian", data = data)
Error in validObject(.Object) : 
  invalid class “dsparseModelMatrix” object: superclass "xMatrix" not defined in the environment of the object's class
````

Am I missing something (dependencies or otherwise?)

Thanks for your amazing work ! :)

**Comment by finnlindgren** [comment]
This is a (temporary) CRAN/binary build issue, see discussion and solution at https://github.com/inlabru-org/inlabru/issues/218

In short, you need to reinstall at least the `MatrixModels` package as packages that link with the `Matrix` package object system do that at build time, so will still be linked to your old version of the `Matrix` package. To complicate things, `MatrixModels` had an update just a few days before the `Matrix` package, so the binary builds seem to be still linked with the old `Matrix` version. On linux, the normal package installation builds from source, so a basic `install.packages("MatrixModels")` should suffice. On Windows and MacOS, you likely need to specifically ask for a source installation with `install.packages("MatrixModels", type="source")` (this requires a properly configured build system on your system).

As noted in the issue discussion linked above, other packages may also be affected. INLA, fmesher, and inlabru are not directly affected, but reinstalling them shouldn't hurt. (But make sure you install INLA as binary package, not from source).

**Comment by CorentinVisee** [comment]
Hi ! 

Thanks for your quick reply! :)
I'll look into it then 

Thanks again!
