### ISSUE TITLE
Intel MKL FATAL ERROR on MacOS

### ISSUE THREAD

**Issue by ErikKusch** [hrue/r-inla#87]
Hiya,

eager to run some INLA from within R, but I am unfortunately getting stuck even running example code. I believe this may be related to issues #84 and #67.

It'd be great if you could help me resolve this. Please let me know if there are any additional steps I can take or information you would like me to provide.

## The Error Message

I have shortened the below console output to keep this issue readable:
```
inla_build: check for unused entries in[/private/var/folders/c9/5tlmp10s517_f5qmn120ctjc0000gp/T/RtmpvDHrQt/file924464a7a624/Model.ini]
inla_INLA_preopt_experimental...
	Strategy = [DEFAULT]
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
INTEL MKL ERROR: .
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.2.dylib.
Error in inla.inlaprogram.has.crashed() : 
  The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
  If this does not help, please contact the developers at <help@r-inla.org>.
```

## The Code Producing the Error

```r
library(INLA)

n = 100; a = 1; b = 1; tau = 100
z = rnorm(n)
eta = a + b*z

scale = exp(rnorm(n))
prec = scale*tau
y = rnorm(n, mean = eta, sd = 1/sqrt(prec))

data = list(y=y, z=z)
formula = y ~ 1+z
result = inla(formula, family = "gaussian", data = data, verbose = TRUE)
```

## Steps Taken So Far

In attempting to resolve this issue I have:
1. updated numpy and nomkl as suggested [here](https://stackoverflow.com/questions/55778337/what-is-intel-mkl-fatal-error-cannot-load-libmkl-core-dylib-while-running-pysp)
2. ran `install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE)` as suggested in #67 
3. ensured that `pkgType == "both"` before installation as suggested in #84 

## My SessionInfo
```
R version 4.3.2 (2023-10-31)
Platform: x86_64-apple-darwin20 (64-bit)
Running under: macOS Sonoma 14.1.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: Europe/Oslo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] INLA_23.11.26 sp_2.1-2      Matrix_1.6-3 

loaded via a namespace (and not attached):
 [1] vctrs_0.6.5        cli_3.6.1          rlang_1.1.2        DBI_1.1.3          KernSmooth_2.23-22 MatrixModels_0.5-3 generics_0.1.3    
 [8] sf_1.0-14          glue_1.6.2         e1071_1.7-13       fansi_1.0.5        grid_4.3.2         classInt_0.4-10    tibble_3.2.1      
[15] lifecycle_1.0.4    compiler_4.3.2     fmesher_0.1.4.9002 dplyr_1.1.4        pkgconfig_2.0.3    Rcpp_1.0.11.6      rstudioapi_0.15.0 
[22] lattice_0.22-5     R6_2.5.1           tidyselect_1.2.0   class_7.3-22       utf8_1.2.4         parallel_4.3.2     pillar_1.9.0      
[29] splines_4.3.2      magrittr_2.0.3     withr_2.5.2        tools_4.3.2        proxy_0.4-27       units_0.8-5  
```

**Comment by hrue** [comment]
Thx for your comment. I haven't seen this library requested by MKL before, so I have added it to the list to be included. 
I switch to static MKL libraries to avoid similar issues in the future. This fix should be available in the next build (testing version)

**Comment by ErikKusch** [comment]
Fab - thanks! Just to double-check: that fix is not rolled out yet, correct? I just downloaded the testing version via 

`install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE, type="mac.binary")`

and receive the same error as before.
