### ISSUE TITLE
INLA crashes across environments

### ISSUE THREAD

**Issue by ErikKusch** [hrue/r-inla#88]
Hiya, me again. Still having troubles. Pardon if it's user error. I would be happy to get INLA to run in any of these environments.

# The Issue

Trying to run INLA across several operating systems, I fail to retrieve a model estimate even for just test code. I am running off of the INLA version 23.11.26 and have tried both stable and testing releases.

# Minimal Working Example & Environments

Here is the code with which I can reliable create the INLA crashes:
```r
library(INLA)

n = 100; a = 1; b = 1; tau = 100
z = rnorm(n)
eta = a + b*z

scale = exp(rnorm(n))
prec = scale*tau
y = rnorm(n, mean = eta, sd = 1/sqrt(prec))

data = list(y=y, z=z)
formula = y ~ 1+z
result = inla(formula, family = "gaussian", data = data, verbose = TRUE)
```

## MacOS

I have already reported my issue on MacOS (issue #87). As far as I can tell, the fix promised there has been made as a [commit](https://github.com/hrue/r-inla/commit/0092cc77a92a7b9c4f843ac27f9ea8a7c36e6304), but not added to any new release yet.

In the meantime, I looked deeper into this issue and believe that even the new fix may not solve this issue as it seems [Intel MKL is not available for M2 chips](https://www.intel.com/content/www/us/en/developer/articles/system-requirements/oneapi-math-kernel-library-system-requirements.html).

Trying to retrieve [mkl from conda](https://anaconda.org/conda-forge/mkl):
```
conda install -c conda-forge mkl
```

I am met with this error:
```
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mkl

Current channels:

  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

## Windows
Switching to a windows server:
```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server 2019 x64 (build 17763)
```

INLA crashes without an informative output despite running with `verbose = TRUE`:
```
Error in inla.inlaprogram.has.crashed() : 
  The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
  If this does not help, please contact the developers at <help@r-inla.org>.
```

## HPC

Finally, in an HPC environment of these specifications:
```
Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-147-generic aarch64)
R/4.2.2-foss-2022b
```

and running `inla.binary.install()`, then selecting the following option:
```
Alternative 5  is  ./Ubuntu-22.04.3 LTS (Jammy Jellyfish)/Version_23.11.26/64bit.tgz
```
```
* Install file [https://inla.r-inla-download.org/Linux-builds/./Ubuntu-22.04.3 LTS (Jammy Jellyfish)/Version_23.11.26/64bit.tgz]
* INLA is installed in [/home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA]
* Checking for write access...
* Download file, please wait...
* md5-checksum [fd45cc5a4785dcc9eb817e98b65c2aa6] OK.
* Rename old 64bit directory...
* Unpack file...
* Remove temporary file...
* Remove old 64bit directory...
* Done!
```

I receive a different error that I cannot parse or resolve, I am afraid:
```
ERROR: ld.so: object '/home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/first/libjemalloc.so.2' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
/home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/inla.mkl.run: line 64: /home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/inla.mkl: cannot execute binary file: Exec format error
/home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/inla.mkl.run: line 70: /home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/inla.mkl: cannot execute binary file: Exec format error
/home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/inla.mkl.run: line 70: /home/erikkus/R/aarch64-unknown-linux-gnu-library/4.2/INLA/bin/linux/64bit/inla.mkl: Success
Error in inla.inlaprogram.has.crashed() :
  The inla-program exited with an error. Unless you interupted it yourself, please rerun with verbose=TRUE and check the output carefully.
  If this does not help, please contact the developers at <help@r-inla.org>.

```

**Comment by hrue** [comment]
I'll build a new version hopefully today, which should solve this on MacOS.

**Comment by hrue** [comment]
For the Ubuntu one, then the binary that follows is compiled with Ubuntu 20.04, so there should not be any need to install another binary.

**Comment by hrue** [comment]
For the Windows one, I have no idea. I have to try with mine

**Comment by ErikKusch** [comment]
Cheers! Afraid the ubuntu issue was present even before running `inla.binary.install()`. I guess there are some modules missing but I can't figure out which.

**Comment by hrue** [comment]
Windows is fine with me.

**Comment by hrue** [comment]
Let's see how this goes with a new version

**Comment by ErikKusch** [comment]
I will hold until the newer version is out. Could you share your windows version and sessioninfo of R therein?

**Comment by hrue** [comment]
Can you try now?

**Comment by ErikKusch** [comment]
Is this what we want to see?
<img width="915" alt="image" src="https://github.com/hrue/r-inla/assets/32892717/187e204f-f86c-45f8-990e-a6d9febf4c36">

Tested on Mac. Going to subsequently test also on HPC and Windows during the day.

**Comment by hrue** [comment]
yes

On Thu, 2023-12-07 at 00:21 -0800, Erik Kusch wrote:
> Is this what we want to see?
> image.png (view on web)
> Tested on Mac. Going to subsequently test also on HPC and Windows
> during the day.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.
