### ISSUE TITLE
INLA installation failed

### ISSUE THREAD

**Issue by hwwbg** [hrue/r-inla#90]
Failed to install from "inla.r-inla-download.org", then try to install it from github with the code below:
```
devtools::install_github(repo = "https://github.com/hrue/r-inla", ref = "stable", subdir = "rinla", build = FALSE)
```
It failed as well:
```
* DONE (INLA)
Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\xxxxx\AppData\Local\Temp\RtmpAdmrzK\file608cd765616.tar.gz" -C "C:/Users/xxxx/AppData/Local/Temp/RtmpAdmrzK/remotes608c3522867"’ returned error code 1
```
Any suggestions how to fix it?
Thanks!

**Comment by hrue** [comment]
follow the install instructions at r-inla.org


On Mon, 2024-01-22 at 12:37 -0800, Haoyu Wu wrote:
> Failed to install from "inla.r-inla-download.org", then try to install
> it from github with the code below:
> devtools::install_github(repo = "https://github.com/hrue/r-inla", ref
> = "stable", subdir = "rinla", build = FALSE)
> It failed as well:
> * DONE (INLA)
> Warning message:
> In utils::untar(tarfile, ...) :
>   ‘tar.exe -xf
> "C:\Users\xxxxx\AppData\Local\Temp\RtmpAdmrzK\file608cd765616.tar.gz"
> -C "C:/Users/xxxx/AppData/Local/Temp/RtmpAdmrzK/remotes608c3522867"’
> returned error code 1
> Any suggestions how to fix it?
> Thanks!
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this
> thread.Message ID: ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by finnlindgren** [comment]
Specifically, see https://www.r-inla.org/download-install

**Comment by hwwbg** [comment]
> follow the install instructions at r-inla.org
> […](#)
> On Mon, 2024-01-22 at 12:37 -0800, Haoyu Wu wrote: Failed to install from "inla.r-inla-download.org", then try to install it from github with the code below: devtools::install_github(repo = "https://github.com/hrue/r-inla", ref = "stable", subdir = "rinla", build = FALSE) It failed as well: * DONE (INLA) Warning message: In utils::untar(tarfile, ...) :   ‘tar.exe -xf "C:\Users\xxxxx\AppData\Local\Temp\RtmpAdmrzK\file608cd765616.tar.gz" -C "C:/Users/xxxx/AppData/Local/Temp/RtmpAdmrzK/remotes608c3522867"’ returned error code 1 Any suggestions how to fix it? Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
> -- Håvard Rue Professor of Statistics Chair of the Statistics Program CEMSE Division King Abdullah University of Science and Technology Thuwal 23955-6900 Kingdom of Saudi Arabia ***@***.*** Office: +966 (0)12 808 0640   Mobile: +966 (0)54 470 0421 Research group: bayescomp.kaust.edu.sa   R-INLA project: [www.r-inla.org](http://www.r-inla.org) Zoom: kaust.zoom.us/my/haavard.rue
> -- This message and its contents, including attachments are intended solely for the original recipient. If you are not the intended recipient or have received this message in error, please notify me immediately and delete this message from your computer system. Any unauthorized use or distribution is prohibited. Please consider the environment before printing this email.

Yes, I did follow the install instruction on the r-inla.org.  I have R4.3.0, so I tried to install 23.05.30. Failed as well.
![image](https://github.com/hrue/r-inla/assets/48967642/a807cf21-4b04-4f04-9cd4-55d66c1d8685)
![image](https://github.com/hrue/r-inla/assets/48967642/479ebf5d-de00-4c51-9c96-b0e02f1d4ff2)

**Comment by chuymtz** [comment]
@hwwbg I'm also running R version 4.3 but slightly different from you. I have 4.3.1. After struggling a little bit the installation command that worked for me was
```
install.packages("INLA",repos=c(getOption("repos"),INLA="https://inla.r-inla-download.org/R/testing"), dep=TRUE) 
```
See if this goes better for you. When I tried the `stable` version I was also getting the same error you are getting.
