### ISSUE TITLE
R 4.4.0 (latest) | Error in inla.call.builtin() : INLA installation error; no such file

### ISSUE THREAD

**Issue by zhengxiaoUVic** [hrue/r-inla#97]
An old issue has recurred. #75 #48 #45 #40 

**R** version 4.4.0 (Puppy Cup) was released on 2024-04-24. However, the current "_R-INLA_" version 24.02.09 is not compatible with **R** 4.4.0.

A temporary fix: downgrade to **R** 4.3.3 (Angel Food Cake, 2024-02-29).

**Comment by finnlindgren** [comment]
The ”stable” version from February is not the latest. The ”testing” version is (24.05.01-1) While it hasn't been built specifically for R 4.4.0 yet, I believe it should install (by the 4.4 section of the repository linking to the 4.3 section). That should let most models run; see for example the inlabru test that run on both 4.4 (“release”) and R-devel: https://github.com/inlabru-org/inlabru/actions/runs/8897647260

if you have trouble with the “testing” versions, please provide your R sessionInfo and OS details, as these issues can be highly platform specific; also show the full R output from the package installation (e.g. make sure you didn’t inadvertently try to install the inla source package on windows/mac, that require the prebuilt binary package.

**Comment by hrue** [comment]
We'll upgrade all builds to R-4.4 in about two weeks time

On Thu, 2024-05-02 at 15:45 -0700, Zhengxiao Wei wrote:
> An old issue has recurred. #75 #48 #45 #40
> R version 4.4.0 (Puppy Cup) was released on 2024-04-24. However, the current
> "R-INLA" version 24.02.09 is not compatible with R 4.4.0.
> A temporary fix: downgrade to R 4.3.3 (Angel Food Cake, 2024-02-29).
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID:
> ***@***.***>

-- 
Håvard Rue
Professor of Statistics
Chair of the Statistics Program
CEMSE Division
King Abdullah University of Science and Technology
Thuwal 23955-6900
Kingdom of Saudi Arabia

***@***.***
Office: +966 (0)12 808 0640  
Mobile: +966 (0)54 470 0421
Research group: bayescomp.kaust.edu.sa  
R-INLA project: www.r-inla.org
Zoom: kaust.zoom.us/my/haavard.rue

-- 

This message and its contents, including attachments are intended solely 
for the original recipient. If you are not the intended recipient or have 
received this message in error, please notify me immediately and delete 
this message from your computer system. Any unauthorized use or 
distribution is prohibited. Please consider the environment before printing 
this email.

**Comment by zhengxiaoUVic** [comment]
From version 24.05.10, INLA is built for R-4.4.
![IMG 0000](https://github.com/hrue/r-inla/assets/89574270/67a2fb47-cde5-45ca-b130-b1e2b813c7d8)
